import { Router } from 'express';
import usersRouter from './users.js';
import coursesRouter from './courses.js';
import teachersRouter from './teachers.js';
import paymentsRouter from './payments.js';
import categoriesRouter from './categories.js';
import adminsRouter from './admins.js';
import authRouter from './auth.js';
import couponsRouter from './coupons.js';
import cmsRouter from './cms.js';
import subscriptionsRouter from './subscriptions.js';
import cartRouter from './cart.js';
import ordersRouter from './orders.js';
import bannersRouter from './banners.js';
import sessionsRouter from './sessions.js';
import examsRouter from './exams.js';
import licensesRouter from './licenses.js';
import ticketsRouter from './tickets.js';
import tasRouter from './tas.js';
import packagesRouter from './packages.js';
import accessRouter from './access.js';
import notificationsRouter from './notifications.js';
import assignmentsRouter from './assignments.js';
import quizzesRouter from './quizzes.js';
import evaluationsRouter from './evaluations.js';

const router = Router();

router.use('/users', usersRouter);
router.use('/courses', coursesRouter);
router.use('/teachers', teachersRouter);
router.use('/payments', paymentsRouter);
router.use('/categories', categoriesRouter);
router.use('/admins', adminsRouter);
router.use('/auth', authRouter);
router.use('/coupons', couponsRouter);
router.use('/cms', cmsRouter);
router.use('/subscriptions', subscriptionsRouter);
router.use('/cart', cartRouter);
router.use('/orders', ordersRouter);
router.use('/banners', bannersRouter);
router.use('/sessions', sessionsRouter);
router.use('/exams', examsRouter);
router.use('/licenses', licensesRouter);
router.use('/tickets', ticketsRouter);
router.use('/tas', tasRouter);
router.use('/packages', packagesRouter);
router.use('/access', accessRouter);
router.use('/notifications', notificationsRouter);
router.use('/assignments', assignmentsRouter);
router.use('/quizzes', quizzesRouter);
router.use('/evaluations', evaluationsRouter);

export default router;
